// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbk2A5_cgbYHM6QSeMyuU-PVMXfIWz7Pk',
    appId: '1:681961006338:web:a1559f78109ee953ac8e1b',
    messagingSenderId: '681961006338',
    projectId: 'first-project-d48a7',
    authDomain: 'first-project-d48a7.firebaseapp.com',
    storageBucket: 'first-project-d48a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnr3IOrJhphojplQmrRw0SY7kLh57bHNo',
    appId: '1:681961006338:android:3bc890f8909b1f27ac8e1b',
    messagingSenderId: '681961006338',
    projectId: 'first-project-d48a7',
    storageBucket: 'first-project-d48a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsdzc_kwNi5JFbtAdw4f9BFTyE0ZvgTc',
    appId: '1:681961006338:ios:fc7a3dc371ebf4b1ac8e1b',
    messagingSenderId: '681961006338',
    projectId: 'first-project-d48a7',
    storageBucket: 'first-project-d48a7.appspot.com',
    iosClientId: '681961006338-g0lru2pbt7539jvbep555a9f0gsd0reu.apps.googleusercontent.com',
    iosBundleId: 'com.aydin.flutterFirebaseDersleri',
  );
}
